---
abstract: 'Build your development environment by perl-based DSL.'
author:
  - 'magnolia <magnolia.k@me.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::Exception: 0
  Test::Output: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Enbld
no_index:
  directory:
    - t
    - inc
    - xt
requires:
  File::Copy::Recursive: 0
  LWP: 0
  LWP::Protocol::https: 0
  Mozilla::CA: 0
  Try::Lite: 0
  perl: 5.012
resources:
  bugtracker: https://github.com/magnolia-k/Enbld/issues
  homepage: https://github.com/magnolia-k/Enbld
  repository: https://github.com/magnolia-k/Enbld.git
version: 0.7022
