--- #YAML:1.0
name:               Enbld
version:            0.7013
abstract:           Build your development environment by perl-based DSL.
author:
    - magnolia <magnolia.k@me.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.56
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.012
resources:
    bugtracker:
        web:  https://github.com/magnolia-k/Enbld/issues
    homepage:  https://github.com/magnolia-k/Enbld
    repository:
        type:  git
        url:   https://github.com/magnolia-k/Enbld.git
        web:   https://github.com/magnolia-k/Enbld
no_index:
    directory:
        - t
        - inc
        - xt
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  2
