---
abstract: 'Build your development environment by perl-based DSL.'
author:
  - 'magnolia <magnolia.k@me.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.56
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Enbld
no_index:
  directory:
    - t
    - inc
    - xt
requires:
  perl: 5.012
version: 0.7011
